services:
  postgres:
    image: postgres:15
    container_name: unishare_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: unishare_db
      POSTGRES_USER: unishare_user
      POSTGRES_PASSWORD: unishare_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: